import {parseCSV,validateCSV,fields} from './contract.mjs';
const $=id=>document.getElementById(id);
let data=null, generation=0, example=false;
function reset(){generation++;data=null;example=false;$('file').value='';$('mapping').replaceChildren();$('preview').textContent='';$('result').replaceChildren();$('file-status').textContent='';$('mapping-panel').hidden=true;$('equipment').value='';$('role').value='';$('role').disabled=false;}
function load(text,name,isExample=false){data=parseCSV(text);example=isExample;$('file-status').textContent=`${name} · ${data.rows.length}행 · ${data.headers.length}열`;$('preview').textContent=[data.headers,...data.rows.slice(0,3)].map(r=>r.join(' | ')).join('\n');$('mapping-panel').hidden=false;
  const labels={board_id:'기판 ID',pad_id:'패드 ID',value:'측정 숫자'};
  for(const f of fields){const label=document.createElement('label');label.textContent=labels[f];const select=document.createElement('select');select.id=`map-${f}`;select.add(new Option('열 선택',''));data.headers.forEach((h,i)=>select.add(new Option(h,String(i))));const match=data.headers.indexOf(f);if(match>=0)select.value=String(match);label.append(select);$('mapping').append(label);}
  $('role').value=example?'synthetic':'';$('role').disabled=example;if(example)$('equipment').value='SYNTHETIC-SPI';
}
$('file').addEventListener('change',async()=>{const file=$('file').files[0];reset();if(!file)return;const token=generation;try{if(!/\.csv$/i.test(file.name)||file.size>5*1024*1024)throw Error('5MB 이하 CSV만 지원합니다.');const bytes=await file.arrayBuffer();if(token!==generation)return;load(new TextDecoder('utf-8',{fatal:true}).decode(bytes),file.name);}catch(e){if(token===generation)$('file-status').textContent=e.message;}});
$('example').addEventListener('click',()=>{reset();load('board_id,pad_id,value\nDEMO-001,P01,120\nDEMO-001,P02,\nDEMO-002,P01,118','합성 예제',true);});
$('clear').addEventListener('click',reset);
$('mapping-panel').addEventListener('change',()=>{$('result').replaceChildren();});
$('mapping-panel').addEventListener('input',()=>{$('result').replaceChildren();});
$('validate').addEventListener('click',()=>{ $('result').replaceChildren();try{if(!data)throw Error('파일을 먼저 선택하세요.');const mapping=Object.fromEntries(fields.map(f=>[f,$(`map-${f}`).value===''?-1:Number($(`map-${f}`).value)]));const report=validateCSV(data,mapping,{equipment:$('equipment').value,role:example?'synthetic':$('role').value,metric:$('metric').value});const title=document.createElement('h2');title.textContent=report.rejected.length?'입력 검증: 수정 필요':'입력 검증 완료 · 분석 미실행';const summary=document.createElement('p');summary.textContent=`형식 통과 ${report.accepted.length}행 / 격리 ${report.rejected.length}행. 실장비 진위·측정 정확도·불량 성능을 검증한 결과가 아닙니다.`;$('result').append(title,summary);const list=document.createElement('ul');report.rejected.slice(0,100).forEach(r=>{const li=document.createElement('li');li.textContent=`데이터 레코드 ${r.record}: ${r.errors.join(' / ')}`;list.append(li);});$('result').append(list);if(report.rejected.length>100){const note=document.createElement('p');note.textContent='오류 목록은 첫 100건만 표시합니다.';$('result').append(note);}}catch(e){$('result').textContent=e.message;}});
